name: Automatic Semantic Releases
author: Oliver Salzburg
description: Automate the GitHub release process with assets, changelogs, pre-releases, and more
branding:
  icon: git-merge
  color: red

inputs:
  repo_token:
    description: GitHub secret token.
    required: true
  automatic_release_tag:
    description: git tag (for automatic releases).
    required: false
  body_prefix:
    description: Text to prepend before the changelog in the release body.
    required: false
  body_suffix:
    description: Text to append after the changelog in the release body.
    required: false
  changelog_artifact:
    description: Name of a file to save the changelog metadata into. Will be attached to the workflow run.
    required: false
  draft:
    description: Should this release be marked as a draft?
    required: false
    default: "false"
  dry_run:
    default: "false"
    description: If set to "true", no tags will be moved.
    required: false
  files:
    description: Assets to upload to the release.
    required: false
  merge_similar:
    default: "true"
    description: Should similar changes be consolidated to take up less space in the changelog?
    required: false
  prerelease:
    description: Should this release be marked as a pre-release?
    required: false
    default: "true"
  title:
    description: Release title (for automatic releases).
    required: false
  with_authors:
    default: "true"
    description: If set to "true", render the names of commit authors, instead of the commit hash.
    required: false
outputs:
  automatic_releases_tag:
    description: The release tag this action just processed.
  upload_url:
    description: The URL for uploading additional assets to the release.
runs:
  using: node20
  main: lib/main.js
