name: Automatic Semantic Releases
author: Oliver Salzburg
description: Automate the GitHub release process with assets, changelogs, pre-releases, and more
branding:
  icon: git-merge
  color: red

inputs:
  repo-token:
    description: GitHub secret token.
    required: true
  automatic-release-tag:
    description: git tag (for automatic releases).
    required: false
  body-prefix:
    description: Text to prepend before the changelog in the release body.
    required: false
  body-suffix:
    description: Text to append after the changelog in the release body.
    required: false
  changelog-artifact:
    description: Name of a file to save the changelog metadata into. Will be attached to the workflow run.
    required: false
  draft:
    default: "false"
    description: Should this release be marked as a draft?
    required: false
  dry-run:
    default: "false"
    description: If set to "true", no tags will be moved. If you also don't want an actual release, disable `publish`.
    required: false
  files:
    description: Assets to upload to the release.
    required: false
  merge-similar:
    default: "true"
    description: Should similar changes be consolidated to take up less space in the changelog?
    required: false
  prerelease:
    default: "true"
    description: Should this release be marked as a pre-release?
    required: false
  publish:
    description: Should we actually publish a GitHub release, or just do other work?
    default: "true"
    required: false
  root-version:
    description: Provide the current version of your project to determine the release version automatically.
    required: false
  title:
    description: Release title (for automatic releases).
    required: false
  with-authors:
    default: "true"
    description: If set to "true", render the names of commit authors, instead of the commit hash.
    required: false
outputs:
  automatic-releases-tag:
    description: The release tag this action just processed.
  commits-total:
    description: Total amount of commits since last release.
  unconventional-total:
    description: Total amount of commits without convention.
  lifecycle-total:
    description: Total amount of commits that fall into the "lifecycle" category.
  major-total:
    description: Total amount of commits that fall into the "major change" category.
  minor-total:
    description: Total amount of commits that fall into the "minor change" category.
  patch-total:
    description: Total amount of commits that fall into the "patch change" category.
  upload-url:
    description: The URL for uploading additional assets to the release.
  version-current:
    description: Current version
  version-dev:
    description: Version suggestion
  version-dev-extended:
    description: Version suggestion
  version-dev-extended-hash:
    description: Version suggestion
  version-dev-hash:
    description: Version suggestion
  version-extension:
    description: Version suggestion
  version-major:
    description: Version suggestion
  version-major-dev:
    description: Version suggestion
  version-major-dev-hash:
    description: Version suggestion
  version-major-extended-dev:
    description: Version suggestion
  version-major-extended-dev-hash:
    description: Version suggestion
  version-major-extended-nightly:
    description: Version suggestion
  version-major-extended-nightly-hash:
    description: Version suggestion
  version-major-nightly:
    description: Version suggestion
  version-major-nightly-hash:
    description: Version suggestion
  version-minor:
    description: Version suggestion
  version-minor-dev:
    description: Version suggestion
  version-minor-dev-hash:
    description: Version suggestion
  version-minor-extended-dev:
    description: Version suggestion
  version-minor-extended-dev-hash:
    description: Version suggestion
  version-minor-extended-nightly:
    description: Version suggestion
  version-minor-extended-nightly-hash:
    description: Version suggestion
  version-minor-hash:
    description: Version suggestion
  version-minor-nightly:
    description: Version suggestion
  version-minor-nightly-hash:
    description: Version suggestion
  version-nightly:
    description: Version suggestion
  version-nightly-extended:
    description: Version suggestion
  version-nightly-extended-hash:
    description: Version suggestion
  version-nightly-hash:
    description: Version suggestion
  version-patch:
    description: Version suggestion
  version-patch-dev:
    description: Version suggestion
  version-patch-dev-hash:
    description: Version suggestion
  version-patch-extended-dev:
    description: Version suggestion
  version-patch-extended-dev-hash:
    description: Version suggestion
  version-patch-extended-nightly:
    description: Version suggestion
  version-patch-extended-nightly-hash:
    description: Version suggestion
  version-patch-hash:
    description: Version suggestion
  version-patch-nightly:
    description: Version suggestion
  version-patch-nightly-hash:
    description: Version suggestion
  version-root:
    description: Current version stripped of extensions.
runs:
  using: node20
  main: lib/main.js
