name: Automatic Semantic Releases
author: Oliver Salzburg
description: Automate the GitHub release process with assets, changelogs, pre-releases, and more
branding:
  icon: git-merge
  color: red

inputs:
  repo-token:
    description: GitHub secret token.
    required: true
  automatic-release-tag:
    description: git tag (for automatic releases).
    required: false
  body-prefix:
    description: Text to prepend before the changelog in the release body.
    required: false
  body-suffix:
    description: Text to append after the changelog in the release body.
    required: false
  changelog-artifact:
    description: Name of a file to save the changelog metadata into. Will be attached to the workflow run.
    required: false
  draft:
    default: "false"
    description: Should this release be marked as a draft?
    required: false
  dry-run:
    default: "false"
    description: If set to "true", no tags will be moved. If you also don't want an actual release, disable `publish`.
    required: false
  files:
    description: Assets to upload to the release.
    required: false
  merge-similar:
    default: "true"
    description: Should similar changes be consolidated to take up less space in the changelog?
    required: false
  prerelease:
    default: "true"
    description: Should this release be marked as a pre-release?
    required: false
  publish:
    description: Should we actually publish a GitHub release, or just do other work?
    default: "true"
    required: false
  root-version:
    description: Provide the current version of your project to determine the release version automatically.
    required: false
  title:
    description: Release title (for automatic releases).
    required: false
  with-authors:
    default: "true"
    description: If set to "true", render the names of commit authors, instead of the commit hash.
    required: false
outputs:
  automatic-releases-tag:
    description: The release tag this action just processed.
  commits-total:
    description: Total amount of commits since last release.
  unconventional-total:
    description: Total amount of commits without convention.
  lifecycle-total:
    description: Total amount of commits that fall into the "lifecycle" category.
  major-total:
    description: Total amount of commits that fall into the "major change" category.
  minor-total:
    description: Total amount of commits that fall into the "minor change" category.
  upload-url:
    description: The URL for uploading additional assets to the release.
  version-current:
    description: Current version in the manifest.
  version-extensions:
    description: Extension that was found on your current manifest version.
  version-dev:
    description: Version number to use for a transient development release.
  version-dev-extended:
    description: Version number to use for a transient development release, including extension.
  version-major:
    description: Version number to use for a major bump.
  version-minor:
    description: Version number to use for a minor bump.
  version-nightly:
    description: Version number to use for a transient nightly release.
  version-nightly-extended:
    description: Version number to use for a transient nightly release, including extensions.
  version-patch:
    description: Version number to use for a patch bump.
  version-root:
    description: Current manifest version stripped of extensions.
runs:
  using: node20
  main: lib/main.js
